### ISSUE TITLE
Create mailing list

### ISSUE THREAD

**Issue by AlbaRoza** [Signalen/signalen.org#34] opened 2020-07-24 15:17 UTC
- Gather everyone interested in Signalen under one mailing list
- Inspiration: https://lists.publiccode.net/mailman/postorius/lists/openzaak-discuss.lists.publiccode.net/ for OpenZaak

**Comment by Ainali** [comment] 2020-07-24 16:42
Is this a duplicate of #29 ?

**Comment by felixfaassen** [comment] 2020-11-02 10:29
Signalen mailing list has been created

**Closed by felixfaassen** 2020-11-02 10:29 UTC
